---

require: rubocop-rails

AllCops:
  # EnabledByDefault: true
  NewCops: enable
  TargetRubyVersion: 3.0.1
  TargetRailsVersion: 7.0.2

Style/Copyright:
  Description: 'Include a copyright notice in each file before any code.'
  Enabled: false
  VersionAdded: '0.30'
  Notice: '^Copyright (\(c\) )?2[0-9]{3} .+'
  AutocorrectNotice: ''

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  IgnoredMethods: ["describe", "context", "feature", "scenario", "let"]

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude:
    - 'db/schema.rb'
  Include:
    - 'app/**/*'
    - 'spec/**/*'

Layout/SpaceInLambdaLiteral:
  Description: 'Checks for spaces in lambda literals.'
  Enabled: false
  EnforcedStyle: require_no_space
  SupportedStyles:
    - require_no_space
    - require_space

Style/Lambda:
  Description: 'Use the new lambda literal syntax for single-line blocks.'
  StyleGuide: '#lambda-multi-line'
  Enabled: false
  EnforcedStyle: line_count_dependent
  SupportedStyles:
    - line_count_dependent
    - lambda
    - literal

Style/LambdaCall:
  Description: 'Use lambda.call(...) instead of lambda.(...).'
  StyleGuide: '#proc-call'
  Enabled: false
  VersionAdded: '0.13'
  VersionChanged: '0.14'
  EnforcedStyle: call
  SupportedStyles:
    - call
    - braces
