---

require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  EnabledByDefault: true
  TargetRubyVersion: 3.1.0
  TargetRailsVersion: 7.0.2

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/ConstantResolution:
  Enabled: false

Style/Documentation:
  Enabled: false

Rails/SchemaComment:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Bundler/GemVersion:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Rails/RefuteMethods:
  Enabled: false

Style/StringHashKeys:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: false

Rails/SaveBang:
  Enabled: false

Layout/SpaceInLambdaLiteral:
  Description: 'Checks for spaces in lambda literals.'
  Enabled: false
  EnforcedStyle: require_no_space
  SupportedStyles:
    - require_no_space
    - require_space

Style/Lambda:
  Description: 'Use the new lambda literal syntax for single-line blocks.'
  StyleGuide: '#lambda-multi-line'
  Enabled: false
  EnforcedStyle: line_count_dependent
  SupportedStyles:
    - line_count_dependent
    - lambda
    - literal

Style/LambdaCall:
  Description: 'Use lambda.call(...) instead of lambda.(...).'
  StyleGuide: '#proc-call'
  Enabled: false
  VersionAdded: '0.13'
  VersionChanged: '0.14'
  EnforcedStyle: call
  SupportedStyles:
    - call
    - braces

Style/Copyright:
  Description: 'Include a copyright notice in each file before any code.'
  Enabled: false
  VersionAdded: '0.30'
  Notice: '^Copyright (\(c\) )?2[0-9]{3} .+'
  AutocorrectNotice: ''

Lint/NumberConversion:
  Enabled: false

