---

require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  EnabledByDefault: true
  TargetRubyVersion: 3.1.0
  TargetRailsVersion: 7.0.2

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/ConstantResolution:
  Enabled: false

Style/Documentation:
  Enabled: false

Rails/SchemaComment:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Bundler/GemVersion:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Rails/RefuteMethods:
  Enabled: false

Style/Copyright:
  Description: 'Include a copyright notice in each file before any code.'
  Enabled: false
  VersionAdded: '0.30'
  Notice: '^Copyright (\(c\) )?2[0-9]{3} .+'
  AutocorrectNotice: ''
